# Generated by Django 3.1 on 2020-10-24 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='buget',
            new_name='budget',
        ),
        migrations.AlterField(
            model_name='film',
            name='world_premiere',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
