# Generated by Django 3.1 on 2020-11-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20201118_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='country_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='country_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='country_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tagline_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tagline_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tagline_ru',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filmstills',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='filmstills',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='filmstills',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='filmstills',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filmstills',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filmstills',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
