# Generated by Django 3.1 on 2020-11-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20201118_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='film',
            name='country_de',
        ),
        migrations.RemoveField(
            model_name='film',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='film',
            name='tagline_de',
        ),
        migrations.RemoveField(
            model_name='film',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='filmstills',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='filmstills',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name_de',
        ),
    ]
